# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lh-hDN1NdVOmuCXaXUswUmeyKBZC4wCs
"""

import streamlit as st
import numpy as np
import joblib

# Load the trained model and scaler
model = joblib.load('titanic_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("Titanic Survival Prediction App")

st.write("This app predicts whether a passenger would survive the Titanic disaster based on their details.")

# User inputs
pclass = st.selectbox("Passenger Class (1 = 1st, 2 = 2nd, 3 = 3rd)", [1, 2, 3])
age = st.slider("Age", 0, 80, 25)
fare = st.number_input("Fare", 0.0, 600.0, 50.0)
sex = st.selectbox("Gender", ["Female", "Male"])
sex_male = 1 if sex == "Male" else 0
embarked = st.selectbox("Port of Embarkation", ["C", "Q", "S"])
embarked_Q = 1 if embarked == "Q" else 0
embarked_S = 1 if embarked == "S" else 0
sibsp = st.number_input("Siblings/Spouses Aboard", 0, 10, 0)
parch = st.number_input("Parents/Children Aboard", 0, 10, 0)

# Prepare input data
X_input = np.array([[pclass, age, fare, sex_male, embarked_Q, embarked_S, sibsp, parch]])
X_scaled = scaler.transform(X_input)

# Make prediction
prediction = model.predict(X_scaled)[0]
probability = model.predict_proba(X_scaled)[0][1]

# Show result
st.subheader("Prediction Result")
if prediction == 1:
    st.success(f"The passenger is predicted to SURVIVE.")
else:
    st.error(f"The passenger is predicted to NOT SURVIVE.")

st.write(f"Survival Probability: {probability*100:.2f}%")